4632 - Adding script tag into the CKAN footer template
GSA/ckanext-datagovtheme pull request #186
Opened 2024-03-01 17:03 UTC by dlennox24

Solves: https://github.com/GSA/data.gov/issues/4632

2024-03-01 17:31 UTC, btylerburton commented
@FuhuXia can we add remote URL's to webassets? https://github.com/GSA/ckanext-datagovtheme/blob/main/ckanext/datagovtheme/fanstatic_library/webassets.yml

2024-03-01 17:47 UTC, btylerburton commented
Good point. What template is it that handles adding the webassets to the bottom of the page? We could add it there.

2024-03-01 18:02 UTC, FuhuXia commented
> Good point. What template is it that handles adding the webassets to the bottom of the page? We could add it there.

Either that, or we can create a wrap js to `$.getScript()` the dap js. 
So the purpose for the change is that you don't like adding an external js in the `<footer>` somewhere in the middle the html body?

2024-03-01 19:38 UTC, btylerburton submitted a review, later dismissed
🧹

2024-03-01 19:42 UTC, FuhuXia requested changes

2024-03-01 19:42 UTC, FuhuXia commented on ckanext/datagovtheme/templates/footer.html
>  </footer>
possible to include instead of a lot of copy/paste?
```suggestion
{% include "snippets/identifier.html" %}
</footer>
```

2024-03-01 19:44 UTC, btylerburton commented
Looks like there is a failure to find this repo for UI test though. I can help troubleshoot more when I'm back on my machine. 

> pull access denied for ckan/ckan-solr-dev, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

2024-03-11 18:30 UTC, FuhuXia submitted a review, later dismissed

2024-03-11 20:19 UTC, FuhuXia submitted a review, later dismissed

2024-03-11 20:20 UTC, FuhuXia commented
Can you deploy the two latest changes to catalog-dev?

2024-03-12 12:54 UTC, tdlowden commented
@FuhuXia do we need to change the branch it's merged into in order to deploy to dev?

2024-03-12 13:53 UTC, jbrown-xentity commented
> do we need to change the branch it's merged into in order to deploy to dev?

@dlennox24 @tdlowden:
You'll need to incorporate these changes into catalog.data.gov repo (see [here](https://github.com/GSA/catalog.data.gov/blob/main/ckan/requirements.txt#L16), and will need to pull directly from this repo and branch instead of pypi, there are other examples in the requirements file). Once you have that in a branch/PR, you can push that to the develop branch using `git push origin branch_name:develop`, and this will use [github action based on the develop branch](https://github.com/GSA/catalog.data.gov/blob/main/.github/workflows/commit.yml#L58-L76). Let me know if we need to pair on this!

2024-03-12 13:59 UTC, jbrown-xentity commented
Also, we'll need to bump the version of this extension in this PR before it get's merged: https://github.com/GSA/ckanext-datagovtheme/blob/main/setup.py#L13

2024-03-12 13:59 UTC, tdlowden commented
Since @dlennox24 is not working on this til Friday but we'd like to progress, maybe we can grab some time together @jbrown-xentity. I have a conflict during pair time today but I'll check your cal!

2024-03-12 16:43 UTC, FuhuXia approved these changes

2024-03-12 16:43 UTC, merged